pub mod algorithms;
pub mod array_utils;
pub mod cluster;
pub mod complement;
pub mod config;
pub mod count_overlaps;
pub mod filter_op;
pub mod grouped_stream;
pub mod interval_tree;
pub mod merge;
pub mod nearest;
pub mod nearest_index;
pub mod overlap;
pub mod physical_planner;
pub mod session_builder;
pub mod subtract;
pub mod table_function;

// Re-export key types
pub use algorithms::Algorithm;
pub use cluster::ClusterProvider;
pub use complement::ComplementProvider;
pub use config::BioConfig;
pub use count_overlaps::CountOverlapsProvider;
pub use filter_op::FilterOp;
pub use merge::MergeProvider;
pub use nearest::NearestProvider;
pub use overlap::OverlapProvider;
pub use physical_planner::IntervalJoinPhysicalOptimizationRule;
pub use physical_planner::RangesQueryPlanner;
pub use physical_planner::joins::interval_join::IntervalJoinExec;
pub use session_builder::{create_ranges_session, create_ranges_session_with_config};
pub use subtract::SubtractProvider;
pub use table_function::register_ranges_functions;
